using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SystemStacjiNarciarskiejDLL;

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddOpenApi();
builder.Services.AddSignalR();

builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy =>
        policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()));

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
var dbPassword = builder.Configuration["DbPassword"];

var npgsqlBuilder = new Npgsql.NpgsqlConnectionStringBuilder(connectionString)
{
    Password = dbPassword
};

builder.Services.AddDbContext<SkiResortDbContext>(options =>
    options.UseNpgsql(npgsqlBuilder.ConnectionString));

var jwtSecret = builder.Configuration["JwtSecret"]!;
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
            ValidateIssuer = false,
            ValidateAudience = false
        };
    });

builder.Services.AddAuthorization();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<SkiResortDbContext>();
    var sql = @"
        CREATE TABLE IF NOT EXISTS dict_lift_status (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL
        );
        CREATE TABLE IF NOT EXISTS dict_trail_status (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL
        );
        INSERT INTO dict_lift_status (name) VALUES ('Otwarty'), ('Zamknięty z powodu warunków'), ('Awaria'), ('Przerwa techniczna') ON CONFLICT DO NOTHING;
        INSERT INTO dict_trail_status (name) VALUES ('Otwarta'), ('Zamknięta') ON CONFLICT DO NOTHING;
        INSERT INTO dict_card_status (id, name) VALUES (4, 'usunieta') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

        ALTER TABLE lift ADD COLUMN IF NOT EXISTS capacity integer NULL;
        ALTER TABLE lift ADD COLUMN IF NOT EXISTS type text NULL;
        ALTER TABLE lift ADD COLUMN IF NOT EXISTS status_id integer NULL;
        
        ALTER TABLE trail ADD COLUMN IF NOT EXISTS snow_condition text NULL;
        ALTER TABLE trail ADD COLUMN IF NOT EXISTS preparation_status text NULL;
        ALTER TABLE trail ADD COLUMN IF NOT EXISTS status_id integer NULL;

        ALTER TABLE lift_schedule ADD COLUMN IF NOT EXISTS season_id integer NULL;
        
        ALTER TABLE tariff ADD COLUMN IF NOT EXISTS discount_type text NULL;
        ALTER TABLE gate ADD COLUMN IF NOT EXISTS last_heartbeat timestamp NULL;
    ";
    try {
        db.Database.ExecuteSqlRaw(sql);
    } catch(Exception e) {
        Console.WriteLine("DB UPGRADE ERROR: " + e.Message);
    }
}

if (app.Environment.IsDevelopment())
    app.MapOpenApi();

// obsługa html, css, js na stronie (folder wwwroot)
app.UseDefaultFiles();
app.UseStaticFiles();

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapHub<SystemAPI.Hubs.InfrastructureHub>("/infrastructureHub");
app.Run();
