// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemStacjiNarciarskiejDLL;

#nullable disable

namespace SystemStacjiNarciarskiejDLL.Migrations
{
    [DbContext(typeof(SkiResortDbContext))]
    [Migration("20260522090545_AddInfrastructureManagement")]
    partial class AddInfrastructureManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.AdminReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("ReportParameters")
                        .HasColumnType("text")
                        .HasColumnName("report_parameters");

                    b.Property<int?>("ReportTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("report_type_id");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("admin_report");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("administrator");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddedToPoolAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_to_pool_at");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text")
                        .HasColumnName("block_reason");

                    b.Property<bool?>("DepositPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("deposit_paid");

                    b.Property<string>("PhysicalCondition")
                        .HasColumnType("text")
                        .HasColumnName("physical_condition");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("card");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("cashier");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictCardStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_card_status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictLiftStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_lift_status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictOperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_operation_type");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictPassStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_pass_status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictPassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_pass_type");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_report_type");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_reservation_status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_season");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictTrailDifficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_trail_difficulty");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictTrailStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_trail_status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.DictVerificationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dict_verification_result");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LiftId")
                        .HasColumnType("integer")
                        .HasColumnName("lift_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.ToTable("gate");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.GateScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int?>("GateId")
                        .HasColumnType("integer")
                        .HasColumnName("gate_id");

                    b.Property<DateTime?>("ScanTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scan_time");

                    b.Property<DateTime?>("TimeBlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_blocked_until");

                    b.Property<int?>("VerificationResultId")
                        .HasColumnType("integer")
                        .HasColumnName("verification_result_id");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GateId");

                    b.HasIndex("VerificationResultId");

                    b.ToTable("gate_scan");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Lift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PlannerId")
                        .HasColumnType("integer")
                        .HasColumnName("planner_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PlannerId");

                    b.HasIndex("StatusId");

                    b.ToTable("lift");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.LiftSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("interval")
                        .HasColumnName("closing_time");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("LiftId")
                        .HasColumnType("integer")
                        .HasColumnName("lift_id");

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("interval")
                        .HasColumnName("opening_time");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("SeasonId");

                    b.ToTable("lift_schedule");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.LiftTrail", b =>
                {
                    b.Property<int>("LiftId")
                        .HasColumnType("integer")
                        .HasColumnName("lift_id");

                    b.Property<int>("TrailId")
                        .HasColumnType("integer")
                        .HasColumnName("trail_id");

                    b.HasKey("LiftId", "TrailId");

                    b.HasIndex("TrailId");

                    b.ToTable("lift_trail");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<string>("ReservationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reservation_number");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.ShiftReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardsIssuedCount")
                        .HasColumnType("integer")
                        .HasColumnName("cards_issued_count");

                    b.Property<int?>("CashierId")
                        .HasColumnType("integer")
                        .HasColumnName("cashier_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal?>("TotalDepositReturns")
                        .HasColumnType("numeric")
                        .HasColumnName("total_deposit_returns");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_revenue");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("shift_report");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.SkiPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockReason")
                        .HasColumnType("text")
                        .HasColumnName("block_reason");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int?>("InitialRides")
                        .HasColumnType("integer")
                        .HasColumnName("initial_rides");

                    b.Property<int?>("RemainingRides")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_rides");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int?>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TariffId");

                    b.ToTable("ski_pass");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PassTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("pass_type_id");

                    b.Property<int?>("PoolLimit")
                        .HasColumnType("integer")
                        .HasColumnName("pool_limit");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int?>("RideCount")
                        .HasColumnType("integer")
                        .HasColumnName("ride_count");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("PassTypeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("tariff");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DifficultyId")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_id");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PlannerId")
                        .HasColumnType("integer")
                        .HasColumnName("planner_id");

                    b.Property<string>("PreparationStatus")
                        .HasColumnType("text")
                        .HasColumnName("preparation_status");

                    b.Property<string>("SnowCondition")
                        .HasColumnType("text")
                        .HasColumnName("snow_condition");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("PlannerId");

                    b.HasIndex("StatusId");

                    b.ToTable("trail");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.TrailPlanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("trail_planner");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.TrailSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClosureReason")
                        .HasColumnType("text")
                        .HasColumnName("closure_reason");

                    b.Property<bool?>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<int?>("TrailId")
                        .HasColumnType("integer")
                        .HasColumnName("trail_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("trail_schedule");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int?>("CashierId")
                        .HasColumnType("integer")
                        .HasColumnName("cashier_id");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_type_id");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("ReservationId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.AdminReport", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Administrator", "Admin")
                        .WithMany("AdminReports")
                        .HasForeignKey("AdminId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictReportType", "ReportType")
                        .WithMany()
                        .HasForeignKey("ReportTypeId");

                    b.Navigation("Admin");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Card", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictCardStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Gate", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Lift", "Lift")
                        .WithMany("Gates")
                        .HasForeignKey("LiftId");

                    b.Navigation("Lift");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.GateScan", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Card", "Card")
                        .WithMany("GateScans")
                        .HasForeignKey("CardId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Gate", "Gate")
                        .WithMany("GateScans")
                        .HasForeignKey("GateId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictVerificationResult", "VerificationResult")
                        .WithMany()
                        .HasForeignKey("VerificationResultId");

                    b.Navigation("Card");

                    b.Navigation("Gate");

                    b.Navigation("VerificationResult");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Lift", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.TrailPlanner", "Planner")
                        .WithMany("Lifts")
                        .HasForeignKey("PlannerId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictLiftStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Planner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.LiftSchedule", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Lift", "Lift")
                        .WithMany("Schedules")
                        .HasForeignKey("LiftId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");

                    b.Navigation("Lift");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.LiftTrail", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Lift", "Lift")
                        .WithMany("LiftTrails")
                        .HasForeignKey("LiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Trail", "Trail")
                        .WithMany("LiftTrails")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lift");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Reservation", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictReservationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.ShiftReport", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Cashier", "Cashier")
                        .WithMany("ShiftReports")
                        .HasForeignKey("CashierId");

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.SkiPass", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Card", "Card")
                        .WithMany("SkiPasses")
                        .HasForeignKey("CardId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Reservation", "Reservation")
                        .WithMany("SkiPasses")
                        .HasForeignKey("ReservationId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictPassStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Tariff", "Tariff")
                        .WithMany("SkiPasses")
                        .HasForeignKey("TariffId");

                    b.Navigation("Card");

                    b.Navigation("Reservation");

                    b.Navigation("Status");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Tariff", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictPassType", "PassType")
                        .WithMany()
                        .HasForeignKey("PassTypeId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");

                    b.Navigation("PassType");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Trail", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictTrailDifficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.TrailPlanner", "Planner")
                        .WithMany("Trails")
                        .HasForeignKey("PlannerId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictTrailStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Difficulty");

                    b.Navigation("Planner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.TrailSchedule", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Trail", "Trail")
                        .WithMany("Schedules")
                        .HasForeignKey("TrailId");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Transaction", b =>
                {
                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Cashier", "Cashier")
                        .WithMany("Transactions")
                        .HasForeignKey("CashierId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.DictOperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("OperationTypeId");

                    b.HasOne("SystemStacjiNarciarskiejDLL.Models.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Cashier");

                    b.Navigation("OperationType");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Administrator", b =>
                {
                    b.Navigation("AdminReports");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Card", b =>
                {
                    b.Navigation("GateScans");

                    b.Navigation("SkiPasses");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Cashier", b =>
                {
                    b.Navigation("ShiftReports");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Gate", b =>
                {
                    b.Navigation("GateScans");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Lift", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("LiftTrails");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Reservation", b =>
                {
                    b.Navigation("SkiPasses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Tariff", b =>
                {
                    b.Navigation("SkiPasses");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.Trail", b =>
                {
                    b.Navigation("LiftTrails");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.TrailPlanner", b =>
                {
                    b.Navigation("Lifts");

                    b.Navigation("Trails");
                });

            modelBuilder.Entity("SystemStacjiNarciarskiejDLL.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
